/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderDrawer: typeof import('./src/components/header/HeaderDrawer.vue')['default']
    HeaderMenu: typeof import('./src/components/header/HeaderMenu.vue')['default']
    LoginCard: typeof import('./src/components/user/LoginCard.vue')['default']
    ProducerCard: typeof import('./src/components/ProducerCard.vue')['default']
    ProducerSearchLine: typeof import('./src/components/ProducerSearchLine.vue')['default']
    ProducerSongSelect: typeof import('./src/components/ProducerSongSelect.vue')['default']
    RegisterCard: typeof import('./src/components/user/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
